config/routes.rb
Rails.application.routes.draw do

get 'signup', to: 'users#new'
resources :pages
resources :card_transactions
resources :oxxo_transactions
resources :purchases
resources :services
resources :users, except: [:new]

get 'miscompras', to:'users#all'
get 'mispendientes', to:'users#processar'
get 'login', to:'sessions#new'
post 'login', to: 'sessions#create'
delete 'logout', to: 'sessions#destroy'
root 'sessions#new'

resources :users

end

app/models/service.rb
class Service < ActiveRecord::Base
    has_many :purchase_services
    has_many :purchases, through: :purchase_services


    validates :nombre, presence: true, length: { minimum: 3, maximum: 50 }
    validates_uniqueness_of :nombre
    validates :precio, presence: true
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  before_action :require_same_user, only: [:edit, :destroy]

  #Ocupar para todos
  before_action :set_user, only: [:edit,:update,:show,:new]


   def index
      @service = Service.all
    end

    def show
      @service = Service.find(params[:id])
      @service_purchase= @service.purchases.all
    end

    def edit
      @category = Category.find(params[:id])
    end



  private
  def category_params
    params.require(:service).permit(:nombre)
  end


  #Ocupar para todos
    def set_user
      @user = User.find(current_user)
    end

    def require_same_user

      if current_user != @ctransaction.user and @user.usuario != 'administrador'
        fash[:danger] = "Solo puedes editar tu cuenta"
        redirect_to user_path(@user)
      end

    end



end

app/views/services/_service.html.erb
<span class="badge" id='trap'> <%= link_to service.nombre,service_path(service) %> &nbsp; </span>

app/views/services/show.html.erb
<h1 class='center'><%= 'Service: '+@service.nombre %></h1>
<div align='center'>

  <%= will_paginate @category_article %>
  <% for item in @service_purchase %>

  <%= item.nombre %>
  <br>
<% end %>




</div>
<!-- <%= render 'articles/article' ,obj: @category_article %>
<div align='center'>
  <%= will_paginate @category_article %>
</div> -->