config/routes.rb
Rails.application.routes.draw do

get 'signup', to: 'users#new'
resources :pages
resources :card_transactions
resources :oxxo_transactions
resources :purchases
resources :services
resources :users, except: [:new]

get 'miscompras', to:'users#all'
get 'mispendientes', to:'users#processar'
get 'login', to:'sessions#new'
post 'login', to: 'sessions#create'
delete 'logout', to: 'sessions#destroy'
root 'sessions#new'

resources :users

end

app/controllers/oxxo_transactions_controller.rb
class OxxoTransactionsController < ApplicationController
  before_action :set_otransaction, only: [:edit, :destroy, :show, :update]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  #Ocupar para todos
  before_action :set_user, only: [:edit,:update,:show,:new]


  def index
      #Este cargara un numero de items o articulos por pagina y podemos decirle cuantos por pagina
      #Para que se vea, en el index de articulos agregamos algunas lineas de codigo
      @otransaction=OxxoTransaction.all
      #@articles=Article.paginate(page: params[:page], per_page: 5)
  end


  def new
      @otransaction=OxxoTransaction.new
  end


  def edit
  end



  def create
      #render plain: params[:article].inspect
      @otransaction=OxxoTransaction.new(otransaction_params)
      @otransaction.status = 0
      @otransaction.user = current_user

       if @otransaction.save
           flash[:success] = "Proceso iniciado! Una vez pagado regresa a ingresar tu codigo"

            redirect_to oxxo_transaction_path(@otransaction)

       else
           render 'new'
       end
  end


  def update

    @user = User.find(current_user)
    #cuando se compren o se gasten baros  [update]:
   #poner esto al principio del update
 @baro_old = @user.cant_baros #cantidad antigua de baros


#-------------------------------------------------------------------------------


      #Si se actualizo la iformacion que se mando en SUBMIT

      @otransaction.update_attribute(:status, 1)
      if @otransaction.update(otransaction2_params)
          flash[:success] = "Compra de baros exitosa"

        #Registro de baros

            tipo_cambio=10

            #@ctlast = CardTransaction.last
            @lct = OxxoTransaction.last
            c_baros = @lct.monto.to_f / tipo_cambio
            cbt = 0.0

            cbt = c_baros + @user.cant_baros.to_f
            #Aumentar la cantidad de baros al usuario
            @user.update_attribute(:cant_baros, cbt)

            #-------------------------------------------------------------------------------
            #poner esto hasta el final del update
            folder_path = "/home/marisol/adminredes/el_baro/Usuarios/" +  @user.usuario #ruta de la carpeta del usuario.
            Dir.glob(folder_path + "/" + @baro_old.to_s).sort.each do |f|
            filename = File.basename(f, File.extname(f))
            File.rename(f, folder_path + "/" + cbt.to_s+ File.extname(f)) #reemplaza el nombre archivo
          end


            redirect_to oxxo_transaction_path(@otransaction)
      else
          render 'edit'
      end
  end



  def show

  end

# ------------------------ OPCIONAL ------------------------
  def destroy

      @otransaction.destroy
      flash[:danger]="La transaccion fue eliminada"
      redirect_to cardtransactions_path
  end



  private

  def set_otransaction
       @otransaction = OxxoTransaction.find(params[:id])
  end

  #Ocupar para todos
    def set_user
      @user = User.find(current_user)
    end




  def otransaction2_params
      params.require(:oxxo_transaction).permit(:codigo_recibido)
  end


  def otransaction_params
      params.require(:oxxo_transaction).permit(:codigo_emitido, :monto, :total)
  end


  def require_same_user

    if current_user != @otransaction.user and @user.usuario != 'administrador'
      fash[:danger] = "Solo puedes editar tu cuenta"
      redirect_to user_path(@user)
    end


  end


end

app/views/oxxo_transactions/_oxxo.html.erb
<% obj.each.with_index do |oxxo_transaction,index| %>

      <%if oxxo_transaction.status == 0%>
      <p>Compra pendiente</p>
      <%= link_to 'Transaccion', edit_oxxo_transaction_path(oxxo_transaction) %>
      <%end%>

        <%= link_to 'Transacción #'+(index+1).to_s, oxxo_transaction_path(oxxo_transaction),{:style=>'color:red;', :class => "css_class"} %>

        <%= oxxo_transaction.monto%>

        <%= oxxo_transaction.total%>

        <strong>Transaccion creada el: </strong><%= oxxo_transaction.created_at %>

<br>
<br>


<% end %>

app/views/oxxo_transactions/edit.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>elbaro</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
    <link rel="stylesheet" href="sidebar.css">
    <%= stylesheet_link_tag    'styles', media: 'all' %>


  </head>
  <body id="background_color">
    <div id="wrapper">

      <!-- Sidebar-->
      <div id="sidebar-wrapper">
        <%= image_tag("logo_large.png", :alt =>"logo" , id:"logo") %>

        <ul class="sidebar-nav">
          <li><%= link_to "Mi cartera", user_path(@user) %></li>
          <li><%= link_to "Servicios", new_purchase_path %></li>
          <li><%= link_to "Comprar baros", page_path(@user) %></li>
          <li><%= link_to "Mis compras", miscompras_path%></li>
          <li><%= link_to 'Cerrar sesion',logout_path, id:'signup',method: :delete %></li>
        </ul>
      </div>

      </div>

      <!-- Page content-->
      <div id="page-content-wrapper">
        <div class="container-fluid">
          <div class="row">
            <div class="col-lg-12">
              <%= image_tag("menu.png", :alt =>"menu" , id:"m",onclick: "togg();") %>

               <!--Grafica de lineas-->
                  <div class="container">
                    <h3 class="titulo">Forma de pago <strong>OXXO</strong></h3>
                    <hr class="title-hr">
                    <div class="row">
                      <div class="col-md-12" >

                        <div id="inner-oxxo-form">
                            <%= image_tag("oxxo.png", :alt =>"oxxo", id:"inner-oxxo-image") %>
                        </div>


            <%= form_for(@otransaction, :html => {class: "form-horizontal", role: "form"}) do |f| %>
            <div id="oxxo-form">
              <div id="pasomary"> <!-- Inicio de paso 1-->
                <br>
                <br>
                <br>
                  <h3 class="center-elements-conversion"><strong>Compra pendiente</strong></h3>
                  <h4 class="center-elements-conversion">Ingresa el código de pago</h4><br>
                  <h6 id="inner-oxxo-paso1">Código:</h6>
                  <%= f.text_field :codigo_recibido,placeholder:"Codigo",class:"el", id: 'money'%>
                  <br>
                  <div style="margin-top:48px; margin-left:70%; ">
                    <%= f.submit name: "Enviar" , class: "btn btn-primary btn-submit" %>
                  </div>


              </div> <!-- Fin de  paso 1-->
          </div> <!-- Fin de oxxo form-->

          <% end %>

</div>
</div> <!-- Fin de row-->

</div>

</div>
</div>
</div>
</div>

</div>


<!--Menu toggle script -->
<script>
function togg(){
$("#wrapper").toggleClass("menuDisplayed"); };
</script>

<%=  javascript_include_tag 'conv'%>

</body>
</html>

app/views/oxxo_transactions/new.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>elbaro</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
    <link rel="stylesheet" href="sidebar.css">
    <%= stylesheet_link_tag    'styles', media: 'all' %>


  </head>
  <body id="background_color">
    <div id="wrapper">

      <!-- Sidebar-->
      <div id="sidebar-wrapper">
        <%= image_tag("logo_large.png", :alt =>"logo" , id:"logo") %>
        <ul class="sidebar-nav">
          <li><%= link_to "Mi cartera", user_path(@user) %></li>
          <li><%= link_to "Servicios", new_purchase_path %></li>
          <li><%= link_to "Comprar baros", page_path(@user) %></li>
          <li><%= link_to "Mis compras", miscompras_path%></li>
          <li><%= link_to 'Cerrar sesion',logout_path, id:'signup',method: :delete %></li>
        </ul>
      </div>



      <!-- Page content-->
      <div id="page-content-wrapper">
        <div class="container-fluid">
          <div class="row">
            <div class="col-lg-12">
              <%= image_tag("menu.png", :alt =>"menu" , id:"m",onclick: "togg();") %>

               <!--Grafica de lineas-->
                  <div class="container">
                    <h3 class="titulo">Forma de pago <strong>OXXO</strong></h3>
                    <hr class="title-hr">
                    <div class="row">
                      <div class="col-md-12" >

                        <div id="inner-oxxo-form">
                            <%= image_tag("oxxo.png", :alt =>"oxxo", id:"inner-oxxo-image") %>
                        </div>

                        <%= form_for(@otransaction, :html => {class: "form-horizontal", role: "form"}) do |f| %>


                        <div id="oxxo-form">
                          <div id="paso2"style="height:450px;">
                            <h3 id="inner-oxxo-lbl">Referencia:</h3>
                            <div id="area-1">
                              <%= f.text_field :codigo_emitido,class:"el", type: 'text', id: "c_e"%>

                            </div>

                            <h6 id="inner-oxxo-instrucc">INSTRUCCIONES</h6>
                            <div id="area-2">
                              <p>1.- Acude a la tienda OXXO más cercana.</p><br>
                              <p>2.- Indica en la caja que quieres realizar un pago <strong>OXXOPay.</strong></p><br>
                              <p>3.- Dicta al cajero el número de referencia en esta fiha para que tecleé directamente en la pantalla de venta.</p><br>
                              <p>4.- Realiza el pago correspondiente con dinero en efectivo.</p><br>
                              <p>5.- Para confirmar tu pago en la plataforma, el cajero te entregará un comprobante impreso.</p><br>
                              <p><strong>Teclea ese numero de verificacion aqui.</strong></p>
                            </div>
                            <div style="margin-top:48px; margin-left:11.5%; ">
                              <%= f.submit name: "Procesar" , class: "btn btn-primary btn-submit" %>
                            </div>
                          </div>
                          <div id="paso1"> <!-- Inicio de paso 1-->
                              <h3 class="center-elements-conversion"><strong>Conversión de divisas</strong></h3>
                              <h4 class="center-elements-conversion">Pesos / Baros</h4><br>
                              <h6 id="inner-oxxo-paso1">Pesos:</h6>
                              <%= f.text_field :monto,placeholder:"Cantidad de baros a cambiar",class:"el", id: 'money'%>
                              <%= image_tag("convert.png", :alt =>"editar",id:'convert_button',onclick:"calcular();") %><br>
                              <hr>
                              <p class="barr" id="b">BAROS: </p>
                              <p class="barr" id="demo"></p><%= f.text_field :total, id: "totl",class:"el", style:"margin-left:55%; margin-top:25px;" %>

                              <br>
                              <br>
                              <br>
                              <button type="button" id="continuarconversion" class="btn btn-primary" style="margin-left:46%; margin-top:3%; visibility:hidden;" onclick="mostrarpaso2();">Continuar</button>
                              <hr>
                            </div> <!-- Fin de  paso 1-->
                        </div> <!-- Fin de oxxo form-->

                        <% end %>

                      </div>
                    </div> <!-- Fin de row-->

                  </div>

                    </div>

            </div>
          </div>
        </div>
      </div>

    </div>


    <!--Menu toggle script -->
   <script>
     function togg(){
     $("#wrapper").toggleClass("menuDisplayed"); };
   </script>

<%=  javascript_include_tag 'conv'%>

  </body>
</html>

app/views/oxxo_transactions/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>elbaro</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
  <link rel="stylesheet" href="sidebar.css">
<link rel="stylesheet" href="comprastyle.css">
  <%= stylesheet_link_tag    'comprastyle', media: 'all' %>

</head>
<body id="background_color">
  <div id="wrapper">

    <!-- Sidebar-->
    <div id="sidebar-wrapper">
      <%= image_tag("logo_large.png", :alt =>"logo" , id:"logo") %>
      <ul class="sidebar-nav">
        <li><%= link_to "Mi cartera", user_path(@user) %></li>
        <li><%= link_to "Servicios", new_purchase_path %></li>
        <li><%= link_to "Comprar baros", page_path(@user)%></li>
        <li><%= link_to "Mis compras", miscompras_path%></li>
        <li><%= link_to 'Cerrar sesion',logout_path, id:'signup',method: :delete %></li>
      </ul>
    </div>

    <!-- Page content-->
    <div id="page-content-wrapper">
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-12">
            <%= image_tag("menu.png", :alt =>"menu" , id:"m",onclick: "togg();") %>

             <!--Grafica de lineas-->
                <div class="container">
                  <h3 class="titulo"><strong>Mi</strong> cartera</h3>
                  <hr class="title-hr">
                  <div class="row">
                      <!-- HEHEHEHEHEHEHEH -->
                    <div class="col-md-12">
                         
                          <!-- Inicio de clase encabezado-->
                      <div class="bannerhead">
                        <h1 class="comprish1" align="center"> COMPRA CON OXXO </h1>
                      </div>
                      <!-- Inicio de contenido -->
                      <div class='well col-xs-8 col-xs-offset-2'>
                      <!-- Inicio de columna central -->
                      <div class="cuerpeson col-md-4">
                        <h5 style="margin-top:15px;">No. referencia: <%= @otransaction.codigo_emitido %></h3><hr>
                        <h5 >Monto:          <%= @otransaction.monto%></h3><hr>
                        <h5 >Total baros: <%= @otransaction.total %></h3><hr>
                        <h5>Fecha de compra: <%= time_ago_in_words(@otransaction.created_at) %></h5><hr>
                  
                      </div> <!--Fin de columna central-->
                    </div>  <!--Fin de contenido -->
                    <h2 align='center' style="margin-top:40px;">Tu compra fue realizada con éxito! </h2>
                  


       
       
       
       
       
                    
                    </div><!-- FIN DE HEHEHEHHEH -->
                  </div>


                </div>

          </div>
        </div>
      </div>
    </div>

    </div>






  <!--Menu toggle script -->
 <script>



   function togg(){
   $("#wrapper").toggleClass("menuDisplayed"); }
 </script>

 <script src="/morris.min.js"></script>





</body>
</html>